model:
  encoder: 'resnet50' #Encoder Model

train:
  batch_size: 32 #Batch Size
  epochs: 100  #Number of epochs
  num_classes: 5  #Number of target classes
  train_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Train_set_RIQA_DR_Labels.csv' #Path to read the training dataset file
  aug_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Augmented_train_set.csv' #Path to read augmented training dataset file
  gpus: 1 #Number of GPUs
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the training set. Options: ['Good', 'Usable', 'Reject']
  lr: 0.001 #Learning Rate
  validation_split: 0.3 #Partition for validation data
  seed: 42
  verbose: True #To print all configurations while running the script
  auto_lr_find: True #Find LR automatically using LR Rate finder 
  lr_scheduling: 'none' #LR Scheduling strategy to be used. Currently implemented ['None', 'cyclic', 'cosine', 'reduce_plateau']

validation:
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the valdation set

test:
  run_eval_on: 'test'  #Run evaluation on which dataset. Options: ['validation', 'test']
  test_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Test_set_RIQA_DR_Labels.csv' #Path to read the test dataset file
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the test set

dataset:
  root_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/data/diabetic-retinopathy-detection/'  #Root path to the images
  RIQA_train_labels: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Annotated RIQA Labels files/train_set_result'  #Path to RIQA labels of training set
  RIQA_test_labels: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Annotated RIQA Labels files/test_set_result'  #Path to RIQA labels of test set

save_model:
  log_model: True
  directory: '../saved_models2/'
  experiment: 'Resnet50_Good_Usable_Reject'

wandb:
  run_name: 'test-run1'
  
