model:
  encoder: 'resnet18'     #Encoder Model
  pretrained: True        #Use ImageNet weights.
  train_all_layers: False #To train all layers of the model
  do_finetune: False      #Perform finetune 

train:
  batch_size: 32          #Batch Size
  epochs: 1               #Number of epochs
  num_classes: 5          #Number of target classes
  train_df_path: '/home/raman/MLP-RIQA/Train_set_RIQA_DR_Labels.csv'  #Path to read the training dataset file
  aug_df_path: '/home/raman/MLP-RIQA/Augmented_train_set.csv'         #Path to read augmented training dataset file
  continuous_train_df_path: '/home/raman/MLP-RIQA/Train_Continuous_Labels.csv'  #Path to read the training file with continuous quality labels
  continuous_test_df_path: '/home/raman/MLP-RIQA/Test_Continuous_Labels.csv'    #Path to read the test file with continuous quality labels
  gpus: 1                 #Number of GPUs
  categorical_partition: True #Options: [True, False, 'Augmented']
  cat_labels: ['Reject']  #Categorical Quality labels to include in the training set. Options: ['Good', 'Usable', 'Reject']
  lr: 0.001               #Learning Rate
  validation_split: 0.3   #Partition for validation data
  seed: 42
  verbose: True           #To print all configurations while running the script
  auto_lr_find: True      #Find LR automatically using LR Rate finder 
  lr_scheduling: 'none'   #LR Scheduling strategy to be used. Currently implemented ['none', 'cyclic', 'cosine', 'reduce_plateau']

validation:
  cat_labels: ['Reject']  #Categorical Quality labels to include in the valdation set

test:
  run_eval_on: 'test'                 #Run evaluation on which dataset. Options: ['validation', 'test']
  test_df_path: '/home/raman/MLP-RIQA/Test_set_RIQA_DR_Labels.csv' #Path to read the test dataset file
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the test set

dataset:
  root_path: '/home/raman/MLP-RIQA/data/diabetic-retinopathy-detection/'                  #Root path to the images
  RIQA_train_labels: '/home/raman/MLP-RIQA/Annotated RIQA Labels files/train_set_result'  #Path to RIQA labels of training set
  RIQA_test_labels: '/home/raman/MLP-RIQA/Annotated RIQA Labels files/test_set_result'    #Path to RIQA labels of test set
  RIQA_continuous_train: '/home/raman/MLP-RIQA/EyePACS_continuous_quality_scores/train_set_regression_result.csv'   #Path to Continuous RIQA labels of training set
  RIQA_continuous_test: '/home/raman/MLP-RIQA/EyePACS_continuous_quality_scores/test_set_regression_result.csv'     #Path to Continuous RIQA labels of test set

save_model:
  log_model: False
  directory: '../saved_models/'
  experiment: 'Reject'
  plotting_dir: '../plots/'
  cmap_title: 'Good_Augmented tested on G_U_R'

wandb:
  run_name: 'test-run1'
  
