model:
  encoder: 'resnet18' #Encoder Model

train:
  batch_size: 32 #Batch Size
  epochs: 1  #Number of epochs
  num_classes: 5  #Number of target classes
  train_df_path: '/home/raman/MLP-RIQA/Train_set_RIQA_DR_Labels.csv' #Path to read the training dataset file
  aug_df_path: '/home/raman/MLP-RIQA/Augmented_train_set.csv' #Path to read augmented training dataset file
  gpus: 1 #Number of GPUs
  cat_labels: ['Good', 'Usable']  #Categorical Quality labels to include in the training set
  lr: 0.001 #Learning Rate
  validation_split: 0.3 #Partition for validation data
  seed: 42
  verbose: True #To print all configurations while running the script

validation:
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the valdation set

test:
  test_df_path: '/home/raman/MLP-RIQA/Test_set_RIQA_DR_Labels.csv' #Path to read the test dataset file
  cat_labels: ['Good', 'Usable', 'Reject']  #Categorical Quality labels to include in the test set

dataset:
  root_path: '/home/raman/MLP-RIQA/data/diabetic-retinopathy-detection/'  #Root path to the images
  RIQA_train_labels: '/home/raman/MLP-RIQA/Annotated RIQA Labels files/train_set_result'  #Path to RIQA labels of training set
  RIQA_test_labels: '/home/raman/MLP-RIQA/Annotated RIQA Labels files/test_set_result'  #Path to RIQA labels of test set

save_model:
  directory: '../saved_models/'
  experiment: 'Good_Augmented_Images'

wandb:
  run_name: 'test-run1'
  